project:
  type: website
  pre-render: ./add-thumbnails.sh
  resources:
    - posts-data.json
    - CV1.png
    - CV2.png

website:
  title: "RhoGAM Boy"
  description: "Immunology & Genetics PhD @ UTSW | 면역학과 유전학을 공부하는 박사과정생의 기록"
  site-url: https://rhogam.bio
  favicon: logo.svg
  google-analytics: "G-BN9QL5KS5M"
  bread-crumbs: true
  navbar:
    logo: logo.svg
    logo-alt: "rhogam.bio logo"
    left:
      - href: index.qmd
        text: Home
      - href: phd-in-us.qmd
        text: PhD in US
      - href: living-in-us.qmd
        text: Living in US
      - href: research.qmd
        text: Research
    right:
      - href: about-me.qmd
        text: About me
      - icon: github
        href: https://github.com/subonge

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    date-format: "D MMM YYYY"
    include-after-body: _restructure.html
    lightbox: true
